# Generated by Django 5.0 on 2024-10-24 06:02

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("boardapp", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="boardmodel",
            old_name="seen",
            new_name="read",
        ),
    ]
