# Generated by Django 5.0 on 2024-10-24 06:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("boardapp", "0002_rename_seen_boardmodel_read"),
    ]

    operations = [
        migrations.AlterField(
            model_name="boardmodel",
            name="good",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="boardmodel",
            name="read",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="boardmodel",
            name="readtext",
            field=models.TextField(blank=True, null=True),
        ),
    ]
