# Generated by Django 5.0 on 2024-10-24 06:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("boardapp", "0003_alter_boardmodel_good_alter_boardmodel_read_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="boardmodel",
            name="good",
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name="boardmodel",
            name="read",
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name="boardmodel",
            name="readtext",
            field=models.TextField(blank=True, default="a", null=True),
        ),
    ]
